name: ramadhan_companion_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.0
  collection: ^1.19.1
  connectivity_plus: ^6.1.5
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_launcher_icons: ^0.14.4
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.3.0
  hijri: ^3.0.0
  hijri_calendar: ^1.0.7+7
  html: ^0.15.6
  http: ^1.5.0
  lottie: ^3.3.1
  provider: ^6.1.5
  pull_to_refresh: ^2.0.0
  quran: ^1.3.3
  quran_api: ^0.1.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  string_similarity: ^2.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/mosque_lottie.json
    - assets/icon/app_icon.jpg
    - assets/icon/masjid_icon.png
    - assets/icon/kaaba_icon.png
    - assets/icon/star_icon.png
    - assets/icon/islamic_calendar_icon.png
    - assets/icon/glitter_icon.png
    - assets/icon/quran_icon.png
    - assets/icon/donation_icon.png
    - assets/lottie/no_internet_lottie.json
    - assets/data/sadaqah.json
    - assets/icon/bookmark_empty_icon.png
    - assets/icon/bookmark_icon.png
    - assets/data/masjid_account.json
    - assets/icon/volume_icon.png
    - assets/icon/volume_outlined_icon.png

  fonts:
    - family: Liter
      fonts:
        - asset: assets/font/Liter-Regular.ttf
    - family: AmiriQuran
      fonts:
        - asset: assets/font/Amiri,Funnel_Display,Liter,Nunito_Sans,Open_Sans/Amiri/Amiri-Bold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.jpg"
  min_sdk_android: 21
