name: ramadhan_companion_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  html: ^0.15.6
  http: ^1.5.0
  lottie: ^3.3.1
  provider: ^6.1.5
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/mosque_lottie.json
    - assets/icon/app_icon.jpg
    - assets/icon/masjid_icon.png
    - assets/icon/kaaba_icon.png
  fonts:
    - family: Liter
      fonts:
        - asset: assets/font/Liter-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.jpg"
  min_sdk_android: 21
